[package]
name = "auth_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
jsonwebtoken = "10.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.37", features = ["full"] }
